version: 2

defaults: &DEFAULTS
  working_directory: ~/DeferredFutures
  environment:
    PKG_NAME: DeferredFutures

v0.6: &POINT_SIX
  docker:
    - image: invenia/julia-ci-extras:0.6-latest

nightly: &NIGHTLY
  docker:
    - image: invenia/julia-ci-extras:latest

test: &TEST
  steps:
    - checkout
    - run:
        name: Test package
        command: |
          julia --depwarn=error -e '
            VERSION >= v"0.7.0-DEV.3656" && using Pkg
            if VERSION >= v"0.7.0-DEV.5183" && (isfile("Project.toml") || isfile("JuliaProject.toml"))
                Pkg.build(); Pkg.test(coverage=true)
            else
                Pkg.update(); Pkg.clone(pwd()); Pkg.build("DeferredFutures"); Pkg.test("DeferredFutures"; coverage=true)
            end'
    - persist_to_workspace:
        root: ~/
        paths:
          - ./

coverage: &COVERAGE
  steps:
    - attach_workspace:
        at: ~/
    - run:
        name: Update Coverage.jl to get Circle CI support
        command: |
          julia -e '
            VERSION >= v"0.7.0-DEV.3656" && using Pkg
            Pkg.checkout("Coverage")
          '
    - run:
        name: Submit Coverage
        command: |
          julia -e '
            VERSION >= v"0.7.0-DEV.3656" && using Pkg
            VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("DeferredFutures"))
            Pkg.add("DeferredFutures"); using Coverage
            Codecov.submit(process_folder())
          '

jobs:
  test_0.6:
    <<: [*DEFAULTS, *POINT_SIX, *TEST]
  test_nightly:
    <<: [*DEFAULTS, *NIGHTLY, *TEST]
  coverage_0.6:
    <<: [*DEFAULTS, *POINT_SIX, *COVERAGE]
  coverage_nightly:
    <<: [*DEFAULTS, *NIGHTLY, *COVERAGE]

workflows:
  version: 2
  linux_env:
    jobs:
      - test_0.6
      - test_nightly
      - coverage_0.6:
          requires:
            - test_0.6
      - coverage_nightly:
          requires:
            - test_nightly
