version: 2

defaults: &DEFAULTS
  working_directory: ~/DeferredFutures

v0.5: &POINT_FIVE
  docker:
    - image: invenia/julia-ci-extras:0.5-latest

v0.6: &POINT_SIX
  docker:
    - image: invenia/julia-ci-extras:0.6-latest

nightly: &NIGHTLY
  docker:
    - image: invenia/julia-ci-extras:latest

test: &TEST
  steps:
    - checkout
    - run:
        name: Build package
        command: julia -e 'Pkg.clone(pwd()); Pkg.build("DeferredFutures")'
    - run:
        name: Test package
        command: julia -e 'Pkg.test("DeferredFutures"; coverage=true)'
    - persist_to_workspace:
        root: ~/
        paths:
          - ./

coverage: &COVERAGE
  steps:
    - attach_workspace:
        at: ~/
    - run:
        name: Update Coverage.jl to get Circle CI support
        command: julia -e 'Pkg.checkout("Coverage")'
    - run:
        name: Submit Coverage
        command: julia -e 'cd(expanduser("~/DeferredFutures")); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  test_0.5:
    <<: [*DEFAULTS, *POINT_FIVE, *TEST]
  test_0.6:
    <<: [*DEFAULTS, *POINT_SIX, *TEST]
  test_nightly:
    <<: [*DEFAULTS, *NIGHTLY, *TEST]
  coverage_0.5:
    <<: [*DEFAULTS, *POINT_FIVE, *COVERAGE]
  coverage_0.6:
    <<: [*DEFAULTS, *POINT_SIX, *COVERAGE]
  coverage_nightly:
    <<: [*DEFAULTS, *NIGHTLY, *COVERAGE]

workflows:
  version: 2
  linux_env:
    jobs:
      - test_0.5
      - test_0.6
      - test_nightly
      - coverage_0.5:
          requires:
            - test_0.5
      - coverage_0.6:
          requires:
            - test_0.6
      - coverage_nightly:
          requires:
            - test_nightly
